# Site wide configuration

title: Devito

description: Devito - Symbolic Finite Difference Computation

# 120x120 px default image used for Twitter summary card
logo: images/DevitoLogo-twitter-summary-card.png

# 400x250 px default teaser image used in image archive grid
teaser: images/DevitoLogo-teaser.png

locale:

baseurl:

production_url : http://devitoproject.org

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Gerard Gorman
  email: g.gorman@imperial.ac.uk
  twitter: gerardjgorman
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
  # disqus-shortname: devitogithubio

# Navigation bar entries and links
navigation:

- title: Documentation
  url: https://www.devitoproject.org/devito/

#- title: Benchmarks
#  url: /benchmarks

- title: Team
  url: /team

- title: Citing
  url: /citing

- title: Publications
  url: /publications

- title: Opportunities
  url: /opportunities

- title: GitHub
  url: http://github.com/devitocodes/devito

- title: Travis
  url: https://travis-ci.org/devitocodes/devito/

- title: Twitter
  url: https://twitter.com/DevitoCodes

include:
    - _static

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
