# Site wide configuration

title: Devito

description: Devito - DSL and compiler framework for automated finite-differences and stencil computation

# 120x120 px default image used for Twitter summary card
logo: images/DevitoLogo-twitter-summary-card.png

# 400x250 px default teaser image used in image archive grid
teaser: images/DevitoLogo-teaser.png

locale:

baseurl:

production_url : http://devitoproject.org

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap


# Site owner
owner:
  name: Gerard Gorman
  email: g.gorman@imperial.ac.uk
  twitter: gerardjgorman
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
  # disqus-shortname: devitogithubio

# Navigation bar entries and links
navigation:

- title: Documentation
  url: https://www.devitoproject.org/devito/index.html

- title: Citing
  url: /citing

- title: Publications
  url: /publications

- title: Opportunities
  url: /opportunities

- title: Sponsors
  url: /sponsors
  
- title: GitHub
  url: http://github.com/devitocodes/devito

- title: FAQ
  url: https://github.com/devitocodes/devito/blob/master/FAQ.md

- title: Contact us
  url: /contact

- title: Commercial
  url: https://www.devitocodes.com

include:
    - _static

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
