# Site wide configuration

title: Open Performance-portablE SeismiC Imaging
description: Open Performance portablE SeismiC Imaging
logo: images/OpesciLogo-twitter-summary-card.png # 120x120 px default image used for Twitter summary card
teaser: images/OpesciLogo-teaser.png # 400x250 px default teaser image used in image archive grid
locale:
baseurl: http://opesci.github.io
production_url : http://opesci.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Gerard Gorman
  email: gerard.j.gorman@gmail.com
  twitter: gerardjgorman
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: opescigithubio


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
