# Site wide configuration

title: OPESCI

description: Open Performance-portable Seismic Imaging

# 120x120 px default image used for Twitter summary card
logo: images/OpesciLogo-twitter-summary-card.png

# 400x250 px default teaser image used in image archive grid
teaser: images/OpesciLogo-teaser.png

locale:

baseurl:

production_url : http://opesci.org

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Gerard Gorman
  email: gerard.j.gorman@gmail.com
  twitter: gerardjgorman
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: opescigithubio

# Navigation bar entries and links
navigation:

- title: Devito
  url: /devito-public

- title: Documentation
  url: http://www.opesci.org/devito

- title: Team
  url: /team

- title: Publications
  url: /publications

- title: GitHub
  url: http://github.com/opesci/devito

- title: Travis
  url: https://travis-ci.org/opesci/devito/

- title: Twitter
  url: https://twitter.com/OpesciProject


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
